"""Derive the ratified-corpus index (program P13, package P13.1).

Mechanical derivation only: this tool copies verbatim first-level headings
and file paths from the ratified corpus. It adds no claims, no summaries,
and no status information. Output is derived documentation -- informative
only (Baseline L-2) -- and is regenerated, never hand-edited.

Per-file RFC status lines are deliberately not copied: RFC dispositions
are recorded in ADR-0004 and indexed in docs/rfc/README.md.

Conventions: docs/program/DOC_DERIVATION_CONVENTIONS.md
"""

from __future__ import annotations

import sys
from pathlib import Path

# The ratified corpus (PROGRAM.md section 2 derivation sources). specs/ is
# excluded: the specifications are In Review, not ratified (blocker B-08).
# Program documents (docs/program/) are plans, not ratified content.
SOURCE_SETS: tuple[tuple[str, str, str], ...] = (
    ("Constitution", "docs/constitution", "*.md"),
    ("Architecture", "docs/architecture", "*.md"),
    ("Decision records (ADRs)", "docs/decisions", "ADR-*.md"),
    ("RFCs (dispositions recorded in ADR-0004)", "docs/rfc", "RFC-*.md"),
)

OUTPUT_PATH = "docs/derived/CORPUS_INDEX.md"

HEADER = """\
# Ratified Corpus Index (derived)

- Artifact class: derived documentation -- informative only, never
  authoritative (Baseline L-2).
- Generated by `tools/docs/derive_corpus_index.py`. Do not edit by hand;
  regenerate instead. The repository sources listed below win on any
  conflict.
- Per-file RFC status lines are deliberately not copied: RFC dispositions
  are recorded in ADR-0004 and indexed in `docs/rfc/README.md`.
"""


def first_heading(path: Path) -> str:
    """Return the file's first line starting with '# ', else its filename."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.name


def derive_index(root: Path) -> str:
    """Return the derived corpus index for the repository at ``root``."""
    sections: list[str] = [HEADER]
    for title, directory, pattern in SOURCE_SETS:
        base = root / directory
        files = sorted(base.glob(pattern)) if base.is_dir() else []
        lines = [f"\n## {title} (`{directory}/`)\n"]
        if not files:
            lines.append("- (no files found)")
        else:
            for f in files:
                rel = f.relative_to(root).as_posix()
                lines.append(f"- `{rel}` -- {first_heading(f)}")
        sections.append("\n".join(lines))
    return "\n".join(sections) + "\n"


def main(argv: list[str]) -> int:
    root = Path(argv[1]) if len(argv) > 1 else Path(".")
    out = root / OUTPUT_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(derive_index(root), encoding="utf-8")
    print(f"wrote {out.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
