"""TEMPORARY diagnostic probe -- NOT part of the permanent test suite.

Added solely to investigate the persistent
``test_committed_derived_output_is_fresh_when_present`` STALE report for
``docs/derived/ID_CROSSREF.md`` on PR #46. It executes the REAL committed
generator (``tools/docs/derive_id_crossref.py``) inside the CI runner and,
on mismatch, prints a complete machine-readable diagnostic (SHA-256
hashes, byte lengths, first differing line, unified diff, final 10
generated lines, trailing-newline status, and the COMPLETE generated
file between unambiguous delimiters) so the exact expected bytes can be
recovered from the Actions log. The committed file is never modified;
the comparison is performed entirely in memory.

This file MUST be removed from PR #46 before merge.
"""

import difflib
import hashlib
from pathlib import Path

import pytest

from tools.docs import derive_id_crossref

BEGIN_DELIM = "=====BEGIN-GENERATED-ID_CROSSREF====="
END_DELIM = "=====END-GENERATED-ID_CROSSREF====="


def test_diag_id_crossref_expected_bytes():
    repo_root = Path(__file__).resolve().parents[1]
    committed_path = repo_root / derive_id_crossref.OUTPUT_PATH
    if not committed_path.is_file():
        pytest.skip("no committed ID_CROSSREF to compare")

    committed_text = committed_path.read_text(encoding="utf-8")
    generated_text = derive_id_crossref.derive_id_crossref(repo_root)

    committed_bytes = committed_text.encode("utf-8")
    generated_bytes = generated_text.encode("utf-8")

    if committed_bytes == generated_bytes:
        print("DIAG: committed ID_CROSSREF matches generator output exactly")
        return

    committed_lines = committed_text.splitlines()
    generated_lines = generated_text.splitlines()

    first_diff_line = None
    for index, (committed_line, generated_line) in enumerate(
        zip(committed_lines, generated_lines), start=1
    ):
        if committed_line != generated_line:
            first_diff_line = index
            break

    print("DIAG committed sha256:", hashlib.sha256(committed_bytes).hexdigest())
    print("DIAG generated sha256:", hashlib.sha256(generated_bytes).hexdigest())
    print("DIAG committed byte length:", len(committed_bytes))
    print("DIAG generated byte length:", len(generated_bytes))
    print("DIAG committed line count:", len(committed_lines))
    print("DIAG generated line count:", len(generated_lines))
    if first_diff_line is not None:
        print("DIAG first differing line number:", first_diff_line)
        print(
            "DIAG committed line:", repr(committed_lines[first_diff_line - 1])
        )
        print(
            "DIAG generated line:", repr(generated_lines[first_diff_line - 1])
        )
    else:
        print(
            "DIAG no differing line within the common prefix;"
            " divergence is length/trailing-bytes only"
        )
    print(
        "DIAG committed ends with newline:", committed_text.endswith("\n")
    )
    print(
        "DIAG generated ends with newline:", generated_text.endswith("\n")
    )
    print("DIAG unified diff (committed -> generated):")
    for diff_line in difflib.unified_diff(
        committed_lines,
        generated_lines,
        fromfile="committed/ID_CROSSREF.md",
        tofile="generated/ID_CROSSREF.md",
        lineterm="",
    ):
        print(diff_line)
    print("DIAG final 10 generated lines (repr):")
    for tail_line in generated_lines[-10:]:
        print(repr(tail_line))
    print(BEGIN_DELIM)
    print(generated_text, end="")
    print(END_DELIM)
    pytest.fail(
        "DIAG: committed docs/derived/ID_CROSSREF.md differs from"
        " derive_id_crossref(repo_root); the complete expected file is in"
        " captured stdout between the BEGIN/END delimiters."
    )
